const state={name:'Shark',age:0,day:1,cash:500,rep:0,fame:0,location:'Atlanta, Georgia',mode:'Casual / Auto',attrs:{charisma:3,intelligence:3,discipline:3,leadership:1},assets:[{name:'Bicycle',value:100},{name:'Low-income apartment',value:0}],markets:{Gold:2650,Silver:31.2,BTC:95000,EURUSD:1.08},news:[]};
const $=id=>document.getElementById(id); const money=n=>'$'+Math.round(n).toLocaleString();
function render(){ $('age').textContent=`Age ${state.age}`; $('day').textContent=`Day ${state.day} / 365`; $('cash').textContent=money(state.cash); $('networth').textContent=money(state.cash+state.assets.reduce((a,x)=>a+x.value,0)); $('rep').textContent=Math.round(state.rep); $('fame').textContent=Math.round(state.fame); $('communityBar').style.width=Math.min(100,state.rep)+'%'; $('communityText').textContent=`Reputation ${Math.round(state.rep)} / 100`;
 $('character').innerHTML=Object.entries(state.attrs).map(([k,v])=>`<div class="asset"><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${v}</strong></div>`).join('')+`<div class="asset"><span>Location</span><strong>${state.location}</strong></div><div class="asset"><span>Trading Mode</span><strong>${state.mode}</strong></div>`;
 $('assets').innerHTML=state.assets.map(a=>`<div class="asset"><span>${a.name}</span><strong>${money(a.value)}</strong></div>`).join('');
 $('marketsList').innerHTML=Object.entries(state.markets).map(([k,v])=>`<div class="asset"><span>${k}</span><strong>${typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):v}</strong></div>`).join('');
 $('newsFeed').innerHTML=state.news.slice().reverse().map(n=>`<article class="news"><b>${n.title}</b><span class="small">Day ${n.day}</span><p>${n.body}</p></article>`).join('')||'<p class="muted">No headlines yet.</p>'; }
function event(){const pool=[
 ['A new local business opens nearby.','Your city is seeing a small wave of entrepreneurial activity.'],['Markets enter a quiet session.','Volatility falls across several major assets.'],['Financial media warns about rising uncertainty.','Risk sentiment is shifting. Experienced players may want to watch leverage.'],['Your family opens a savings account for you.','Your financial journey starts with a small lesson in compounding.']];const e=pool[Math.floor(Math.random()*pool.length)]; $('events').innerHTML=`<div class="event"><strong>${e[0]}</strong><p>${e[1]}</p></div>`;state.news.push({day:state.day,title:e[0],body:e[1]});}
function advance(){state.day++; if(state.day>365){state.day=1;state.age++;} if(state.age>4){state.rep+=Math.random()*.15;} if(Math.random()<.08) event(); Object.keys(state.markets).forEach(k=>{const v=state.markets[k];state.markets[k]=v*(1+(Math.random()-.5)*.006)}); render();}
function start(){state.name=$('name').value||'Shark';state.location=$('location').value;document.querySelectorAll('.attr').forEach(i=>state.attrs[i.dataset.key]=Math.max(0,Math.min(10,Number(i.value)||0)));if(Object.values(state.attrs).reduce((a,b)=>a+b,0)!==10)return alert('Allocate exactly 10 points.');$('setup').classList.add('hidden');$('game').classList.remove('hidden');event();render();}
document.querySelectorAll('.attr').forEach(i=>i.addEventListener('input',()=>{let total=[...document.querySelectorAll('.attr')].reduce((a,x)=>a+(Number(x.value)||0),0);$('points').textContent=`${total} / 10`; }));
$('start').onclick=start; $('advance').onclick=advance; $('post').onclick=()=>{if(state.age<13)return alert('Social fame unlocks as you age.');state.fame+=1+state.attrs.charisma*.25;state.rep+=.5;state.cash+=10+state.fame*.02;state.news.push({day:state.day,title:'Your post gains attention',body:`Your audience is responding to your content from ${state.location}.`});render();};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabpage').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$(b.dataset.tab).classList.remove('hidden');});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.rep+=.2;render();});
render();